NguyenVietTu_211200970/Models/ErrorViewModel.cs
namespace NguyenVietTu_211200970.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

NguyenVietTu_211200970/Models/HangHoa.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace NguyenVietTu_211200970.Models
{
    public partial class HangHoa
    {
        public int MaHang { get; set; }
        public int MaLoai { get; set; }

        [Required(ErrorMessage = "Tên hàng không được để trống.")]
        public string TenHang { get; set; }

        [Range(100, 5000, ErrorMessage = "Giá phải nằm trong khoảng từ 100 đến 5000.")]
        public decimal? Gia { get; set; }

        [RegularExpression(@"\.(jpg|png|gif|tiff)$", ErrorMessage = "Tên file ảnh phải có đuôi: .jpg, .png, .gif, .tiff")]
        public string Anh { get; set; }

        public virtual LoaiHang MaLoaiNavigation { get; set; }
    }
}

NguyenVietTu_211200970/Models/LoaiHang.cs
using System;
using System.Collections.Generic;

namespace NguyenVietTu_211200970.Models
{
    public partial class LoaiHang
    {
        public LoaiHang()
        {
            HangHoas = new HashSet<HangHoa>();
        }

        public int MaLoai { get; set; }
        public string TenLoai { get; set; } = null!;

        public virtual ICollection<HangHoa> HangHoas { get; set; }
    }
}

NguyenVietTu_211200970/Models/QLHangHoaContext.cs
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;

namespace NguyenVietTu_211200970.Models
{
    public partial class QLHangHoaContext : DbContext
    {
        public QLHangHoaContext()
        {
        }

        public QLHangHoaContext(DbContextOptions<QLHangHoaContext> options)
            : base(options)
        {
        }

        public virtual DbSet<HangHoa> HangHoas { get; set; } = null!;
        public virtual DbSet<LoaiHang> LoaiHangs { get; set; } = null!;
        public virtual DbSet<TblAccount> TblAccounts { get; set; } = null!;

        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            if (!optionsBuilder.IsConfigured)
            {
                optionsBuilder.UseSqlServer("Data Source=DESKTOP-VK77CN3\\SQLEXPRESS;Initial Catalog=QLHangHoa;User ID=sa;Password=123");
            }
        }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<HangHoa>(entity =>
            {
                entity.HasKey(e => e.MaHang);

                entity.ToTable("HangHoa");

                entity.Property(e => e.Anh).HasMaxLength(100);

                entity.Property(e => e.Gia).HasColumnType("numeric(18, 0)");

                entity.Property(e => e.TenHang).HasMaxLength(50);

                entity.HasOne(d => d.MaLoaiNavigation)
                    .WithMany(p => p.HangHoas)
                    .HasForeignKey(d => d.MaLoai)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK_HangHoa_LoaiHang");
            });

            modelBuilder.Entity<LoaiHang>(entity =>
            {
                entity.HasKey(e => e.MaLoai);

                entity.ToTable("LoaiHang");

                entity.Property(e => e.TenLoai).HasMaxLength(50);
            });

            modelBuilder.Entity<TblAccount>(entity =>
            {
                entity.HasKey(e => e.Uid);

                entity.ToTable("tblAccount");

                entity.Property(e => e.Password)
                    .HasMaxLength(10)
                    .IsFixedLength();

                entity.Property(e => e.Username)
                    .HasMaxLength(10)
                    .IsFixedLength();
            });

            OnModelCreatingPartial(modelBuilder);
        }

        partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
    }
}

NguyenVietTu_211200970/Models/TblAccount.cs
using System;
using System.Collections.Generic;

namespace NguyenVietTu_211200970.Models
{
    public partial class TblAccount
    {
        public int Uid { get; set; }
        public string? Username { get; set; }
        public string? Password { get; set; }
    }
}

NguyenVietTu_211200970/Controllers/HomeController.cs
using NguyenVietTu_211200970.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace NguyenVietTu_211200970.Controllers
{
	public class HomeController : Controller
	{
        private QLHangHoaContext db;
        public HomeController(QLHangHoaContext context)
        {
            db = context;
        }

        public IActionResult Index()
		{
			IEnumerable<HangHoa> list_hh = db.HangHoas.Where(hh => hh.Gia > 100).ToList();
			return View("NguyenVietTu_mainContent", list_hh);
		}


		public IActionResult MatHangByLoaiHangID(int mid)
		{
			var lh = db.HangHoas.Where(l => l.MaLoai == mid).ToList();
			return PartialView("TableHangHoa", lh);
		}

		public IActionResult AddToCart()
		{
            ViewBag.CategoryId = new SelectList(db.LoaiHangs, "MaLoai", "TenLoai");
            return View();
		}


        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult AddToCart(HangHoa hh)
        {
            if (!ModelState.IsValid)
            {
                db.HangHoas.Add(hh);
                db.SaveChanges();

                return RedirectToAction("Index");
            }

            return View("AddToCart");
        }

    }
}

NguyenVietTu_211200970/ViewComponents/NavViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using NguyenVietTu_211200970.Models;

namespace NguyenVietTu_211200970.ViewComponents
{
	public class NavViewComponent : ViewComponent
	{
		QLHangHoaContext db;
        List<LoaiHang> majors;
        public NavViewComponent(QLHangHoaContext _context)
        {
            db = _context;
            majors = db.LoaiHangs.ToList();
        }
        public async Task<IViewComponentResult> InvokeAsync()
        {
            return View("RenderNav", majors);
        }
	}
}

NguyenVietTu_211200970/Views/Home/AddToCart.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@

@{
    Layout = "~/Views/Shared/NguyenVietTu_Layout.cshtml";
    ViewData["Title"] = "create";

}


@model HangHoa
<h1>Create</h1>
<div>
    <div asp-validation-summary="All" class="text-danger"></div>
    <form asp-controller="Home" asp-action="AddToCart" method="post" class="mt-3">
        <div class="form-group">
            <label for="Category">Category</label>
            <select asp-for="MaLoai" class="custom-select mr-sm-2"
                    asp-items="@ViewBag.CategoryId"></select>
        </div>
        <div style="margin-top:7px" class="form-group row">
            <label asp-for="TenHang" class="col-sm-2 col-form-label"></label>
            <div class="col-sm-10">
                <input asp-for="TenHang" class="form-control" placeholder="Last Name">
            </div>
            <span asp-validation-for="TenHang" class="text-danger"></span>
        </div>
        
        <div style="margin-top:7px" class="form-group row">
            <label asp-for="Gia" class="col-sm-2 col-form-label"></label>
            <div class="col-sm-10">
                <input asp-for="Gia" class="form-control">
            </div>
            <span asp-validation-for="Gia" class="text-danger"></span>
        </div>
        <div style="margin-top:7px" class="form-group row">
            <label asp-for="Anh" class="col-sm-2 col-form-label"></label>
            <div class="col-sm-10">
                <input asp-for="Anh" class="form-control">
            </div>
            <span asp-validation-for="Anh" class="text-danger"></span>
        </div>
        <div style="margin-top:10px" class="form-group row">
            <div class="col-sm-10">
                <button type="submit" class="btn btn-primary">Create</button>
            </div>
        </div>
    </form>
</div>

NguyenVietTu_211200970/Views/Home/NguyenVietTu_mainContent.cshtml
@{
    ViewData["Title"] = "Home Page";
}


@model IEnumerable<HangHoa>
<!-- Begin Wrap -->
<div class="wrap">
	<!-- Begin Header -->
	<!-- End Header -->
	<!-- Begin Main -->
	<div class="main">
		<div class="content">
			<!-- Begin New Product -->
			
			<!-- End New Product -->
			<!-- Begin Feature Products -->
			<div class="content_bottom">
				<div class="heading">
					<h3>NguyenVietTu</h3>
				</div>
				<div class="see">
					<p><a href="#">See all Products</a></p>
				</div>
				<div class="clear"></div>
			</div>
			<div class="section group">
				@foreach (HangHoa hh in Model)
				{
				<div class="grid_1_of_4 images_1_of_4">
					<a href="preview.html"><img src="images/@hh.Anh" alt="" /></a>
					<h2>@hh.TenHang</h2>
					<div class="price-details">
						<div class="price-number">
							<p><span class="rupees">$@hh.Gia</span></p>
						</div>
						<div class="add-cart">
							<h4><a href="preview.html">Add to Cart</a></h4>
						</div>
						<div class="clear"></div>
					</div>
				</div>
					
				}

				
			</div>
			<!-- End Feature Products -->
		</div>
	</div>
	<!-- End Main -->
</div>
<!-- End Wrap -->
<!-- Begin Footer -->
<!-- End Footer -->
@section Scripts {

    <script>


		$('body').on('click', '#nav_lh', function (e) {
			const mid = $(this).data("id");
			console.log(mid)
			$.ajax({
				url: "/Home/MatHangByLoaiHangID",
				data: {mid},
				success: function (response) {
					$(".section.group").html(response);
				}
			});	

			
		});
        

    </script>
}

NguyenVietTu_211200970/Views/Home/TableHangHoa.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

@model IEnumerable<HangHoa>


@foreach (HangHoa hh in Model)
{
	<div class="grid_1_of_4 images_1_of_4">
		<a href="preview.html"><img src="images/@hh.Anh" alt="" /></a>
		<h2>@hh.TenHang</h2>
		<div class="price-details">
			<div class="price-number">
				<p><span class="rupees">$@hh.Gia</span></p>
			</div>
			<div class="add-cart">
				<h4><a href="preview.html">Add to Cart</a></h4>
			</div>
			<div class="clear"></div>
		</div>
	</div>

}

NguyenVietTu_211200970/Views/Shared/Components/Nav/RenderNav.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}


@model IEnumerable<LoaiHang>

<ul style="color: white">
		<li class="active"><a href="index.html">NguyenVietTu</a></li>
	@foreach(var ll in Model)
	{
		<li id="nav_lh"  data-id="@ll.MaLoai"><a >@ll.TenLoai</a></li>
	}
	
</ul>

NguyenVietTu_211200970/Views/Shared/NguyenVietTu_Footer.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}


<div class="footer">
	<div class="wrap">
		<div class="section group">
			<div class="col_1_of_4 span_1_of_4">
				<h4>Information</h4>
				<ul>
					<li><a href="about.html">About Us</a></li>
					<li><a href="contact.html">Customer Service</a></li>
					<li><a href="#">Advanced Search</a></li>

				</ul>
			</div>
			<div class="col_1_of_4 span_1_of_4">
				<h4>Why buy from us</h4>
				<ul>
					<li><a href="about.html">About Us</a></li>
					<li><a href="contact.html">Customer Service</a></li>
					<li><a href="#">Privacy Policy</a></li>

				</ul>
			</div>
			<div class="col_1_of_4 span_1_of_4">
				<h4>My account</h4>
				<ul>
					<li><a href="contact.html">Sign In</a></li>
					<li><a href="index.html">View Cart</a></li>
					<li><a href="#">My Wishlist</a></li>

				</ul>
			</div>
			<div class="col_1_of_4 span_1_of_4">
				<h4>Contact</h4>
				<ul>
					<li><span>+91-123-456789</span></li>
					<li><span>+00-123-000000</span></li>
				</ul>
			</div>
		</div>
	</div>
</div>
	

NguyenVietTu_211200970/Views/Shared/NguyenVietTu_Header.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}


<div class="header">
	<div class="header_top">
		<div class="logo">
			<a href="index.html"><img src="images/logo.png" alt="" /></a>
		</div>
		<div class="cart">
			<p>
				Welcome to our Online Store! <span>Cart:</span><div id="dd" class="wrapper-dropdown-2">
					0 item(s) - $0.00
					<ul class="dropdown">
						<li>you have no items in your Shopping cart</li>
					</ul>
				</div>
			</p>
		</div>
		<div class="clear"></div>
	</div>
	<div class="header_bottom">
		<div class="menu">
			@await Component.InvokeAsync("Nav");

		</div>
		<div class="search_box">
			<form>
				<input type="text" value="Search" onfocus="this.value = '';" onblur="if (this.value == '') {this.value = 'Search';}">
				<input type="button" value="">
			</form>
		</div>
		<div class="clear"></div>
	</div>
</div>

NguyenVietTu_211200970/Views/Shared/NguyenVietTu_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/KiemtraGiuaKy.styles.css" asp-append-version="true" />
    <title>Free Home Shoppe Website Template | Home :: w3layouts</title>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
    <link href="css/style.css" rel="stylesheet" type="text/css" media="all" />
</head>
<body>

    <partial name="NguyenVietTu_Header" />


    @RenderBody()

    <partial name="NguyenVietTu_Footer" />


    

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>